### ISSUE TITLE
Incorrect httpclient dependency version in glacieruploader-impl

### ISSUE THREAD

**Issue by sonofanickel** [MoriTanosuke/glacieruploader#52]
Just wanted to leave a note here.

I tried listing my vaults and got the following error:

````
**$** java -jar glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar -s
INFO  Using end point: https://glacier.us-east-1.amazonaws.com
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/conn/socket/ConnectionSocketFactory
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.<init>(ApacheHttpClientFactory.java:42)
        at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:141)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:162)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:153)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:138)
        at com.amazonaws.services.glacier.AmazonGlacierClient.<init>(AmazonGlacierClient.java:248)
        at com.amazonaws.services.glacier.AmazonGlacierClient.<init>(AmazonGlacierClient.java:227)
        at de.kopis.glacier.commands.AbstractCommand.<init>(AbstractCommand.java:51)
        at de.kopis.glacier.commands.CreateVaultCommand.<init>(CreateVaultCommand.java:41)
        at de.kopis.glacier.GlacierUploader.findAndExecCommand(GlacierUploader.java:105)
        at de.kopis.glacier.GlacierUploader.main(GlacierUploader.java:70)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.socket.ConnectionSocketFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 11 more
````

To resolve this I had to change the dependency of org.apache.httpcomponents.httpclient inside glacieruploader-impl's pom.xml to use version 4.5.2. This appears to already be done in the parent pom.

**Comment by MoriTanosuke** [comment]
Thanks for the report @sonofanickel. I removed the dependency version from the POM, it was already set in the parent POM as you said. :+1:

**Comment by sonofanickel** [comment]
Anytime. Thanks for writing and publishing this!
