### ISSUE TITLE
can't download or view inventory

### ISSUE THREAD

**Issue by dwiest** [MoriTanosuke/glacieruploader#53]
I'm having troubles downloading archived files and viewing the vault's inventory.

Downloads just hang and no target file is created.

$ java -jar ./glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar --download LA_z3GZKbJdeJnaZV5Ur5UihRfuX8zWu-cm2n1ioRxDubpyVqWrylTklCrteec0VQKQrOb9GbIhOmDFpNjknnIw5FVXbe66XK4c2PkR1tDJ1PiKs-luab4GZiYvPQg04xiRX3DuPeg --target /home/dwiest/test
INFO  Using end point: https://glacier.us-east-1.amazonaws.com
INFO  Downloading archive LA_z3GZKbJdeJnaZV5Ur5UihRfuX8zWu-cm2n1ioRxDubpyVqWrylTklCrteec0VQKQrOb9GbIhOmDFpNjknnIw5FVXbe66XK4c2PkR1tDJ1PiKs-luab4GZiYvPQg04xiRX3DuPeg from vault Test...

I get a job id back when I try to list the vault's inventory, but I can't view the job's results.

$ java -jar ./glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar --list-inventory
INFO  Using end point: https://glacier.us-east-1.amazonaws.com
INFO  Starting inventory listing for vault Test...
INFO  Inventory Job created with ID
Vk5Auz3lAPjikTtDy817MfZrSZohQYuAMa8h1NCe-y-Wh7m-7actsG7hFuKgl8xlZ5lwY4CgzqaFg2cr0VxkNuF1mpyN

[dwiest@prod-sftp-01 ~]$ java -jar ./glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar --list-inventory Vk5Auz3lAPjikTtDy817MfZrSZohQYuAMa8h1NCe-y-Wh7m-7actsG7hFuKgl8xlZ5lwY4CgzqaFg2cr0VxkNuF1mpyN
INFO  Using end point: https://glacier.us-east-1.amazonaws.com
INFO  Retrieving inventory for job id Vk5Auz3lAPjikTtDy817MfZrSZohQYuAMa8h1NCe-y-Wh7m-7actsG7hFuKgl8xlZ5lwY4CgzqaFg2cr0VxkNuF1mpyN...
ERROR The job is not currently available for download: Vk5Auz3lAPjikTtDy817MfZrSZohQYuAMa8h1NCe-y-Wh7m-7actsG7hFuKgl8xlZ5lwY4CgzqaFg2cr0VxkNuF1mpyN (Service: AmazonGlacier; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: cBdo5-aAYrNxvTwl4YGpMlwdBr4HusDpATFTB4e1whXs1ro)
com.amazonaws.services.glacier.model.InvalidParameterValueException: The job is not currently available for download: Vk5Auz3lAPjikTtDy817MfZrSZohQYuAMa8h1NCe-y-Wh7m-7actsG7hFuKgl8xlZ5lwY4CgzqaFg2cr0VxkNuF1mpyN (Service: AmazonGlacier; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: cBdo5-aAYrNxvTwl4YGpMlwdBr4HusDpATFTB4e1whXs1ro)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1386)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:939)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:465)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:427)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:376)
	at com.amazonaws.services.glacier.AmazonGlacierClient.doInvoke(AmazonGlacierClient.java:3290)
	at com.amazonaws.services.glacier.AmazonGlacierClient.invoke(AmazonGlacierClient.java:3259)
	at com.amazonaws.services.glacier.AmazonGlacierClient.getJobOutput(AmazonGlacierClient.java:1536)
	at de.kopis.glacier.commands.ReceiveArchivesListCommand.retrieveInventoryListing(ReceiveArchivesListCommand.java:52)
	at de.kopis.glacier.commands.ReceiveArchivesListCommand.exec(ReceiveArchivesListCommand.java:74)
	at de.kopis.glacier.GlacierUploader.findAndExecCommand(GlacierUploader.java:123)
	at de.kopis.glacier.GlacierUploader.main(GlacierUploader.java:70)

**Comment by dwiest** [comment]
After reading the Glacier FAQ, it seems that I shouldn't expect a job to complete any sooner than 3 hours which explains the hanging client.

**Comment by MoriTanosuke** [comment]
The error message from the Amazon SDK says

    ERROR The job is not currently available for download: Vk5Auz3lAPjikTtDy817MfZrSZohQYuAMa8h1NCe-y-Wh7m-7actsG7hFuKgl8xlZ5lwY4CgzqaFg2cr0VxkNuF1mpyN (Service: AmazonGlacier; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: cBdo5-aAYrNxvTwl4YGpMlwdBr4HusDpATFTB4e1whXs1ro)

@dwiest I'll close this issue. If you have this problem even after the job is available, please re-open.
