### ISSUE TITLE
Exceptions on multipart upload

### ISSUE THREAD

**Issue by alacevedo** [MoriTanosuke/glacieruploader#55]
Hi,
I made a multipart upload of a file and got some connections exceptions like this:

```
INFO  Part 378/393 (bytes 6325010432-6341787647/*) uploaded, checksum: 78f12cb8a20d5228937c881fb61635601aa6f31600857d54c575497939ef8b61
INFO  Part 379/393 (bytes 6341787648-6358564863/*) uploaded, checksum: 8dd1f864bfb627f6a5f26a5ce159bb4bf536ca473e5c7412b33bc048323da973
INFO  Unable to execute HTTP request: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
....
INFO  Part 380/393 (bytes 6358564864-6375342079/*) uploaded, checksum: fb5e8d8ec6d4fbf1cb1a296e22d47ab941230f8cb992ce57f87533443144e36f
INFO  Part 381/393 (bytes 6375342080-6392119295/*) uploaded, checksum: 0085299047da43ffd1db18e6d73a5f34e73bcdaf675dd96b8ed06c4863df710b
INFO  Part 382/393 (bytes 6392119296-6408896511/*) uploaded, checksum: 5d75528e5b9a42aeb292317efbf068a6c0192af23b0635722becf15084265c44
INFO  Part 393/393 (bytes 6576668672-6584865875/*) uploaded, checksum: 854f1a7886fabe7082a3ab61913b512b0818bf78600df19b3ea6a1018d29f370
INFO  Uploaded Archive ID: UPFXHXsHKmNp1VQgP3hSlKk_1zHVrzosnPjQwCMtI2WvFE4VhQpWqxhg0ByvGNoBy1xzQeFClojerdU3O7CZGBbIMyg5rDsWKweD9iAGXDTl4tLn_syYo_II2bb-14CGdYlBHLkHag
INFO  Local Checksum: 97339a098836c8d2fc5e486c476e1e9cb5dd79117fa8b24706d5d181aa0c7c94
INFO  Remote Checksum: 97339a098836c8d2fc5e486c476e1e9cb5dd79117fa8b24706d5d181aa0c7c94
INFO  Checksums are identical, upload succeeded.
```
However the local and remote checksum are the same.

So, glacieruploader retry the connection without a retry message or my file is incomplete in glacier?

Thanks in advance for your answer.

**Comment by MoriTanosuke** [comment]
@alacevedo Any chance you still have the full log file with the stacktrace?

**Comment by alacevedo** [comment]
I only have the command line output:

[glacier-uploader-multipart.txt](https://github.com/MoriTanosuke/glacieruploader/files/1180204/glacier-uploader-multipart.txt)

I can upload the same file again with more flags in the command if you need it.

Thanks!

**Comment by MoriTanosuke** [comment]
Here's the relevant part from the logfile:

````
...
INFO  Part 15/393 (bytes 234881024-251658239/*) uploaded, checksum: 79e25085c00d0a549c4091c18c14afa82783c51aec3ab637835d8e65ae6ad9cf
INFO  Unable to execute HTTP request: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:876)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:847)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:169)
	at org.apache.http.impl.conn.LoggingSessionOutputBuffer.write(LoggingSessionOutputBuffer.java:74)
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:119)
	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:102)
	at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:153)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:98)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:122)
	at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:271)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:257)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:47)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:712)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:517)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:685)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
	at com.amazonaws.services.glacier.AmazonGlacierClient.invoke(AmazonGlacierClient.java:2143)
	at com.amazonaws.services.glacier.AmazonGlacierClient.uploadMultipartPart(AmazonGlacierClient.java:1777)
	at de.kopis.glacier.commands.UploadMultipartArchiveCommand.uploadParts(UploadMultipartArchiveCommand.java:154)
	at de.kopis.glacier.commands.UploadMultipartArchiveCommand.upload(UploadMultipartArchiveCommand.java:73)
	at de.kopis.glacier.commands.UploadMultipartArchiveCommand.exec(UploadMultipartArchiveCommand.java:213)
	at de.kopis.glacier.GlacierUploader.findAndExecCommand(GlacierUploader.java:111)
	at de.kopis.glacier.GlacierUploader.main(GlacierUploader.java:59)
INFO  Part 16/393 (bytes 251658240-268435455/*) uploaded, checksum: 6f3b585e2ab7127eed10704271b951ac7ae9722f712ef759e0aef75811cdffd2
...
````

**Comment by MoriTanosuke** [comment]
There is a retry loop with 5 rounds in the code: [UploadMultipartArchiveCommand.java#L143][0]. There are a couple of different exception in the log file, but don't see anything that looks like the upload aborted. Unfortunately the code does not print out any information about retries yet.

According to the log file and the visible log messages `INFO  Part XX/YYY (bytes ZZZ/*) uploaded...` I assume that the code did retry and eventually completed the upload. Otherwise the logfile would include a message like `Failed operation` and `Something went wrong with the Amazon Client` (see [UploadMultipartArchiveCommand.java#L93][1]).

@alacevedo Did you download the file and check if it is corrupted? I'd say the upload looks good and the file should be ok.

I'll add some more debug output to the code in question, so next time the log file will include a bit more information about this.

[0]: https://github.com/MoriTanosuke/glacieruploader/blob/beaabb66d0dafeea9540b1f2702b4d7a68f151ab/glacieruploader-command/src/main/java/de/kopis/glacier/commands/UploadMultipartArchiveCommand.java#L143
[1]: https://github.com/MoriTanosuke/glacieruploader/blob/beaabb66d0dafeea9540b1f2702b4d7a68f151ab/glacieruploader-command/src/main/java/de/kopis/glacier/commands/UploadMultipartArchiveCommand.java#L93

**Comment by MoriTanosuke** [comment]
Added the retry count to the log message in 62f8d5f0af97e3be6995f1a4e892e3f68c753816
