### ISSUE TITLE
Build failure: Failed to execute goal org.owasp:dependency-check-maven:3.1.2:check

### ISSUE THREAD

**Issue by DaveJarvis** [MoriTanosuke/glacieruploader#72]
# Overview
The `mvn package` command fails to build a package as per the build instructions given.

# Replicate
Reproduce the problem as follows:

```
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
$ mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /opt/maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /opt/jdk1.8.0_201/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-arch1-1-arch", arch: "amd64", family: "unix"
$ mkdir -p $HOME/dev/java
$ cd $HOME/devjava
$ git clone https://github.com/MoriTanosuke/glacieruploader/
$ cd glacieruploader
$ mvn package
...
[INFO] glacieruploader-parent ............................. FAILURE [ 20.151 s]
...
[INFO] BUILD FAILURE
...
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.1.2:check (owasp-check-dependencies) on project glacieruploader-parent: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during dependency-check analysis
```

Build works:

```
$ mvn compile
[INFO] Reactor Summary for glacieruploader-parent 0.1.2-SNAPSHOT:
[INFO] glacieruploader-parent ............................. SUCCESS [  0.666 s]
[INFO] glacieruploader-printers ........................... SUCCESS [  0.480 s]
[INFO] glacieruploader-parsers ............................ SUCCESS [  0.029 s]
[INFO] glacieruploader-command ............................ SUCCESS [  0.064 s]
[INFO] glacieruploader-impl ............................... SUCCESS [  0.109 s]
[INFO] BUILD SUCCESS
```

**Comment by MoriTanosuke** [comment]
When running `mvn package -X` I get the following output:

````
[INFO] If you are behind a proxy you may need to configure dependency-check to use the proxy.
org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2019.xml.gz; unable to connect.
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:177)
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:93)
        at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:151)
        at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2019.xml.gz; received response code 403.
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:158)
        ... 7 more
org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz; unable to connect.
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:177)
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:93)
        at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:151)
        at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz; received response code 403.
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:158)
        ... 7 more
````

Something is odd with the webserver providing the CVE database at https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz: `received response code 403`

I'll try with the most recent version of the OWASP plugin. If that doesn't work I'll move the OWASP check into a profile and remove it from the default build process.

**Comment by MoriTanosuke** [comment]
Could be related to https://github.com/jeremylong/DependencyCheck/issues/1558
