### ISSUE TITLE
v0.1.1 launching with --help flag crashes with "region can not be NULL" error

### ISSUE THREAD

**Issue by bazzilic** [MoriTanosuke/glacieruploader#79]
Just downloaded from Releases page and tried to take a look at the help output, but it crashes.

```
bazzilic@X1CARBON $ java -jar .\glacieruploader-impl-0.1.1-jar-with-dependencies.jar -h
ERROR Region is not configured.
Exception in thread "main" java.lang.NullPointerException: region can not be NULL
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
        at de.kopis.glacier.GlacierUploader.findAndExecCommand(GlacierUploader.java:117)
        at de.kopis.glacier.GlacierUploader.main(GlacierUploader.java:94)

bazzilic@X1CARBON $ java -jar .\glacieruploader-impl-0.1.1-jar-with-dependencies.jar --help
ERROR Region is not configured.
Exception in thread "main" java.lang.NullPointerException: region can not be NULL
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
        at de.kopis.glacier.GlacierUploader.findAndExecCommand(GlacierUploader.java:117)
        at de.kopis.glacier.GlacierUploader.main(GlacierUploader.java:94)

bazzilic@X1CARBON $ java -jar .\glacieruploader-impl-0.1.1-jar-with-dependencies.jar -?
ERROR Region is not configured.
Exception in thread "main" java.lang.NullPointerException: region can not be NULL
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
        at de.kopis.glacier.GlacierUploader.findAndExecCommand(GlacierUploader.java:117)
        at de.kopis.glacier.GlacierUploader.main(GlacierUploader.java:94)
```

**Comment by mrensan** [comment]
Hi 
Based on the documentation, you can add `--region us-east-1` to your commands or add it permanently to your config file: `.glacieruploaderrc`

**Comment by bazzilic** [comment]
Yeah, I figured as much, but this is clearly a bug by any definition, so probably should be fixed.
